networks:
  internal_net:
    driver: bridge

services:
  # ... (resto igual)
  core:
    container_name: core-dev
    build:
      context: .
      target: dev
    volumes:
      - ./core:/app
      - ./auth/config/jwt/public.pem:/app/config/jwt/public.pem:ro
    command: ["symfony", "serve", "--no-tls", "--allow-http", "--listen-ip=0.0.0.0", "--port=80"]
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://root:root@db:3306/donwok?serverVersion=8.0"
      MERCURE_URL: http://gateway/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost/.well-known/mercure
      # Token JWT prefirmado con la clave '!ChangeMe!' para publicar en cualquier t√≥pico
      #MERCURE_JWT_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.yL_7v_QC_ZAnZisrv9shAtv_9lsIDZ6Be_id_id_id_i"
      MERCURE_JWT_SECRET: "secret-key-must-be-at-least-32-chars-long-1234"
    networks:
      - internal_net

  mercure:
    image: dunglas/mercure
    container_name: mercure-hub
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "secret-key-must-be-at-least-32-chars-long-1234"
      MERCURE_SUBSCRIBER_JWT_KEY: "secret-key-must-be-at-least-32-chars-long-1234"
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins *
    networks:
      - internal_net

  gateway:
    image: nginx:alpine
    container_name: gateway-pos
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - core
      - auth
      - mercure
    networks:
      - internal_net

  auth:
    container_name: auth-dev
    build:
      context: .
      target: dev
    volumes:
      - ./auth:/app
      - ./auth/config/jwt:/app/config/jwt:rw
    command: ["symfony", "serve", "--no-tls", "--allow-http", "--listen-ip=0.0.0.0", "--port=80"]
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://root:root@db:3306/donwok_auth?serverVersion=8.0"
    networks:
      - internal_net

  frontend:
    container_name: frontend-symfony
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    command: ["symfony", "serve", "--no-tls", "--allow-http", "--listen-ip=0.0.0.0", "--port=80"]
    networks:
      - internal_net

  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    volumes:
      - ./db_data:/var/lib/mysql:rw
    networks:
      - internal_net
