
services:
  # =====================
  # BACKEND / CORE - DEV
  # =====================
  core:
    container_name: core-dev
    build:
      context: .
      target: dev
    volumes:
      - ./core:/app
      - ./auth/config/jwt/public.pem:/app/config/jwt/public.pem:ro
    command: ["symfony", "serve", "--no-tls", "--allow-http", "--listen-ip=0.0.0.0", "--port=80"]
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://root:root@db:3306/donwok?serverVersion=8.0"
      JWT_PUBLIC_KEY: /app/config/jwt/public.pem
      AUTH_BASE_URL: http://auth
      CORE_SERVICE_NAME: core
      CORE_SERVICE_SECRET: super-secret-core-key
      
      # Mercure Config
      MERCURE_URL: http://gateway/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost/.well-known/mercure
      MERCURE_JWT_SECRET: "secret-key-must-be-at-least-32-chars-long-1234"
    networks:
      - internal_net

  # =====================
  # AUTH - DEV
  # =====================
  auth:
    container_name: auth-dev
    build:
      context: .
      target: dev
    volumes:
      - ./auth:/app
      - ./auth/config/jwt:/app/config/jwt:rw
    command: ["symfony", "serve", "--no-tls", "--allow-http", "--listen-ip=0.0.0.0", "--port=80"]
    environment:
      APP_ENV: dev
      JWT_PRIVATE_KEY: /app/config/jwt/private.pem
      JWT_PUBLIC_KEY: /app/config/jwt/public.pem
      JWT_ISSUER: auth-service
      JWT_AUDIENCE: core-service
      JWT_TTL: 600
      DATABASE_URL: "mysql://root:root@db:3306/donwok_auth?serverVersion=8.0"
      CORE_SERVICE_NAME: core
      CORE_SERVICE_SECRET: super-secret-core-key
    networks:
      - internal_net

  # =====================
  # FRONTEND (SYMFONY)
  # =====================
  frontend:
    container_name: frontend-symfony
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    command: ["symfony", "serve", "--no-tls", "--allow-http", "--listen-ip=0.0.0.0", "--port=80"]
    networks:
      - internal_net

  # =====================
  # MERCURE HUB (Tiempo Real)
  # =====================
  mercure:
    image: dunglas/mercure
    container_name: mercure-hub
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "secret-key-must-be-at-least-32-chars-long-1234"
      MERCURE_SUBSCRIBER_JWT_KEY: "secret-key-must-be-at-least-32-chars-long-1234"
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins *
    networks:
      - internal_net

  # =====================
  # GATEWAY
  # =====================
  gateway:
    image: nginx:alpine
    container_name: gateway-pos
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - core
      - auth
      - mercure
    networks:
      - internal_net

  # =====================
  # DATABASE
  # =====================
  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    ports:
      - "3306:3306" # Acceso directo a BD
    volumes:
      - ./db_data:/var/lib/mysql:rw
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge