
networks:
  internal_net:
    driver: bridge

services:
  # =====================
  # BACKEND / CORE - DEV
  # =====================
  backend:
    container_name: core-dev
    build:
      context: .
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://symfony:symfony@db:3306/app"
    networks:
      - internal_net

  # =====================
  # AUTH - DEV
  # =====================
  auth:
    container_name: auth-dev
    build:
      context: .
      target: dev
    volumes:
      - ./auth:/app
      - ./auth/config/jwt:/app/config/jwt:rw
    ports:
      - "8001:8000"
    environment:
      APP_ENV: dev
      JWT_PRIVATE_KEY: /app/config/jwt/private.pem
      JWT_PUBLIC_KEY: /app/config/jwt/public.pem
      JWT_ISSUER: auth-service
      JWT_AUDIENCE: core-service
      JWT_TTL: 600
      DATABASE_URL: "mysql://symfony:symfony@db:3306/app"
    networks:
      - internal_net

  # =====================
  # BACKEND / CORE - PROD
  # =====================
  # backend_prod:
  #   container_name: core-prod
  #   build:
  #     context: .
  #     target: prod
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db
  #   environment:
  #     APP_ENV: prod
  #     APP_DEBUG: 0
  #     DATABASE_URL: "mysql://symfony:symfony@db:3306/app"
  #   networks:
  #     - internal_net

  # =====================
  # AUTH - PROD
  # =====================
  # auth_prod:
  #   container_name: auth-prod
  #   build:
  #     context: .
  #     target: prod
  #   volumes:
  #     - ./auth:/app
  #     - ./auth/config/jwt:/app/config/jwt:ro
  #   environment:
  #     APP_ENV: prod
  #     APP_DEBUG: 0
  #     JWT_PRIVATE_KEY: /app/config/jwt/private.pem
  #     JWT_PUBLIC_KEY: /app/config/jwt/public.pem
  #     JWT_ISSUER: auth-service
  #     JWT_AUDIENCE: core-service
  #     JWT_TTL: 600
  #   networks:
  #     - internal_net

  # =====================
  # DATABASE
  # =====================
  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal_net
