framework:
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true
        name: CORESESSID
        cookie_secure: false
        cookie_httponly: true
        cookie_samesite: none
        cookie_path: /

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
